#version 450
#extension GL_GOOGLE_include_directive : require
#ifndef LOCAL_X
#define LOCAL_X 8
#endif
#ifndef LOCAL_Y
#define LOCAL_Y 16
#endif
layout(local_size_x = LOCAL_X, local_size_y = LOCAL_Y) in;
layout(binding = 0, rgba16f) uniform readonly image2D inputImage;
layout(binding = 1, rgba8) uniform writeonly image2D outputImage;
#include "color/cst.glsl"
void main() {
    ivec2 p = ivec2(gl_GlobalInvocationID.xy);
    ivec2 n = imageSize(inputImage);
    if (any(greaterThanEqual(p, n))) return;
    vec3 ap1 = max(imageLoad(inputImage, p).rgb, vec3(0.0));
    vec3 dwgDi = rawrCst(ap1, 1u, 0u, 2u, 2u);
    vec3 outc = rawrCst(dwgDi, 2u, 2u, 0u, 1u);
    imageStore(outputImage, p, vec4(clamp(outc, 0.0, 1.0), 1.0));
}
