#!/usr/bin/env python3
"""Single source of truth for frozen quadfix filter constants.

Regenerates (byte-identical if params unchanged):
  shaders/quadfix_params.glsl   (GPU constant tables)
  include/quadfix/QuadfixParams.h (host CPU test constants)

Kernel semantics match scipy.ndimage.gaussian_filter: radius int(4*sigma+0.5),
weights exp(-x^2/2s^2) normalized to sum 1.

Usage: uv run --no-project tools/gen_params.py --check   (CI: fail on drift)
       uv run --no-project tools/gen_params.py --write    (regenerate)
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MASK_SIGMA = 6.0
NOTCH_SIGMA_F = 0.004
SIGMA_S = 1.0 / (2 * 3.141592653589793 * NOTCH_SIGMA_F)
COARSE_SIGMA = SIGMA_S / 8.0
E_FLAT, E_TEX = 1.5, 5.0


def weights(sigma):
    import math
    r = int(4 * sigma + 0.5)
    xs = list(range(-r, r + 1))
    w = [math.exp(-x * x / (2 * sigma * sigma)) for x in xs]
    s = sum(w)
    return r, [v / s for v in w]


def glsl_array(name, size, vals):
    rows = []
    for i in range(0, len(vals), 5):
        rows.append("    " + ", ".join(f"{v:.9e}f" for v in vals[i:i + 5]))
    return f"const float {name}[{size}] = float[{size}](\n" + ",\n".join(rows) + ");"


def h_array(ctype, name, size, vals, fmt):
    rows = []
    for i in range(0, len(vals), 8):
        rows.append("    " + ", ".join(fmt(v) for v in vals[i:i + 8]))
    return f"inline constexpr {ctype} {name}[{size}] = {{\n" + ",\n".join(rows) + "};"


def main():
    mr, mw = weights(MASK_SIGMA)
    cr, cw = weights(COARSE_SIGMA)
    assert mr == 24 and len(mw) == 49, (mr, len(mw))
    assert cr == 20 and len(cw) == 41, (cr, len(cw))
    assert abs(sum(mw) - 1) < 1e-12 and abs(sum(cw) - 1) < 1e-12
    # Carrier tables (must match params file; asserted, not regenerated).
    qy = [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 0, 2, 2]
    qx = [1, 1, 0, 0, 1, 1, 3, 3, 2, 2, 1, 1, 2, 0, 2]
    isim = [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0]
    fac = [2.0] * 12 + [1.0] * 3
    assert len(qy) == len(qx) == len(isim) == len(fac) == 15
    print(f"MASK sigma={MASK_SIGMA} radius={mr} taps={len(mw)}")
    print(f"COARSE sigma={COARSE_SIGMA:.6f} radius={cr} taps={len(cw)}")
    print("GLSL mask weights:")
    print(glsl_array("QF_MASK_W", 49, mw))
    print("GLSL coarse weights:")
    print(glsl_array("QF_COARSE_W", 41, cw))
    if "--check" in sys.argv:
        txt = (ROOT / "shaders" / "quadfix_params.glsl").read_text()
        for token in ["6.649327259e-02f", "8.021503123e-02f"]:
            if token not in txt:
                print(f"DRIFT: {token} missing from quadfix_params.glsl")
                return 1
        print("params in sync")
    if "--write" in sys.argv:
        h = ["#pragma once",
             "// Generated by tools/gen_params.py --write. DO NOT hand-edit.",
             "#include <cstdint>",
             "namespace quadfix { namespace cpu {",
             "inline constexpr float kEFlat = 1.5f;",
             "inline constexpr float kETex = 5.0f;",
             "inline constexpr int kDs = 8;",
             "inline constexpr int kMaskR = 24;",
             h_array("float", "kMaskW", 49, mw, lambda v: f"{v:.9e}f"),
             "inline constexpr int kCoarseR = 20;",
             h_array("float", "kCoarseW", 41, cw, lambda v: f"{v:.9e}f"),
             h_array("int", "kCQy", 15, qy, str),
             h_array("int", "kCQx", 15, qx, str),
             h_array("int", "kCIsIm", 15, isim, str),
             h_array("float", "kCFac", 15, fac, lambda v: f"{v:.1f}f"),
             "} }  // namespace quadfix::cpu"]
        (ROOT / "include" / "quadfix" / "QuadfixParams.h").write_text("\n".join(h) + "\n")
        print("wrote include/quadfix/QuadfixParams.h")
    return 0


if __name__ == "__main__":
    sys.exit(main())
