#version 450
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(set = 0, binding = 0, r16ui) uniform readonly uimage2D srcRaw;
layout(set = 0, binding = 1, r16ui) uniform writeonly uimage2D dstRaw;

void main() {
    ivec2 p = ivec2(gl_GlobalInvocationID.xy);
    ivec2 extent = imageSize(dstRaw);
    if (p.x >= extent.x || p.y >= extent.y) return;
    imageStore(dstRaw, p, imageLoad(srcRaw, p));
}
