add_library(zsl_container STATIC src/ZslContainer.cpp)
add_library(rawr::zsl_container ALIAS zsl_container)
target_include_directories(zsl_container PUBLIC include)
target_compile_features(zsl_container PUBLIC cxx_std_17)
target_compile_options(zsl_container PRIVATE -Wall -Wextra -Wpedantic -Werror)

option(ZSL_CONTAINER_BUILD_TESTS "Build zsl_container tests" OFF)
if(ZSL_CONTAINER_BUILD_TESTS)
  enable_testing()
  add_executable(zsl_container_test tests/zsl_container_test.cpp)
  target_link_libraries(zsl_container_test PRIVATE rawr::zsl_container)
  target_compile_features(zsl_container_test PRIVATE cxx_std_17)
  target_compile_options(zsl_container_test PRIVATE -Wall -Wextra -Wpedantic -Werror)
  add_test(NAME zsl_container_test COMMAND zsl_container_test)
endif()
