#pragma once
// Header-only CPU reference of the quadfix shader chain, for host testing
// only (tests/validate.cpp vs tests/data goldens). Mirrors the GLSL in
// shaders/*.comp pass for pass, in float32 with clamp-to-edge borders:
//   guide (exact 9x9 median or separable fast) -> energy box9 ->
//   Gabor demod/block-mean/downsample -> coarse gaussian -> remod/blend
//   with sigma-6 smoothed texture mask.
// Constants come from QuadfixParams.h (generated by tools/gen_params.py).
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <vector>

#include "quadfix/QuadfixParams.h"

namespace quadfix {
namespace cpu {

inline int clampI(int v, int lo, int hi) { return v < lo ? lo : (v > hi ? hi : v); }

struct Image {
    int w = 0, h = 0;
    std::vector<float> px;
    float at(int x, int y) const { return px[clampI(y, 0, h - 1) * w + clampI(x, 0, w - 1)]; }
    // Phase-preserving neighborhood load: clamp in same-color plane coords.
    // Clamping full-res coords directly can flip parity at the border and
    // pull a different-color pixel into the window (caught by goldens).
    float phaseAt(int x, int y, int dx, int dy) const {
        const int ox = x & 1, oy = y & 1;
        const int pj = clampI((x >> 1) + dx, 0, (w >> 1) - 1);
        const int pi = clampI((y >> 1) + dy, 0, (h >> 1) - 1);
        return px[(2 * pi + oy) * w + (2 * pj + ox)];
    }
};

inline float median9(float v[9]) {
    for (int i = 0; i < 9; ++i)
        for (int j = i + 1; j < 9; ++j)
            if (v[j] < v[i]) std::swap(v[i], v[j]);
    return v[4];
}

inline void guidePass(const Image& in, Image& guide, bool fast) {
    for (int y = 0; y < in.h; ++y)
        for (int x = 0; x < in.w; ++x) {
            if (!fast) {
                float v[81];
                int n = 0;
                for (int dy = -4; dy <= 4; ++dy)
                    for (int dx = -4; dx <= 4; ++dx) v[n++] = in.phaseAt(x, y, dx, dy);
                for (int i = 0; i <= 40; ++i) {
                    int m = i;
                    for (int j = i + 1; j < 81; ++j)
                        if (v[j] < v[m]) m = j;
                    std::swap(v[i], v[m]);
                }
                guide.px[y * in.w + x] = v[40];
            } else {
                float rows[9];
                for (int dy = -4; dy <= 4; ++dy) {
                    float r[9];
                    for (int dx = -4; dx <= 4; ++dx) r[dx + 4] = in.phaseAt(x, y, dx, dy);
                    rows[dy + 4] = median9(r);
                }
                guide.px[y * in.w + x] = median9(rows);
            }
        }
}

inline void energyPass(const Image& in, const Image& guide, Image& energy) {
    for (int y = 0; y < in.h; ++y)
        for (int x = 0; x < in.w; ++x) {
            double s = 0;
            for (int dy = -4; dy <= 4; ++dy)
                for (int dx = -4; dx <= 4; ++dx) {
                    float r = in.phaseAt(x, y, dx, dy) - guide.phaseAt(x, y, dx, dy);
                    s += double(r) * double(r);
                }
            energy.px[y * in.w + x] = float(std::sqrt(s / 81.0));
        }
}

// Coarse field: 15 channels x 4 phases (phase verrrry last: [ch][ph]).
struct Coarse {
    int w = 0, h = 0;
    std::vector<float> px;  // [15][4][h][w]
    float& at(int ch, int ph, int x, int y) { return px[(ch * 4 + ph) * w * h + y * w + x]; }
    float get(int ch, int ph, int x, int y) const {
        return px[(ch * 4 + ph) * w * h + clampI(y, 0, h - 1) * w + clampI(x, 0, w - 1)];
    }
};

inline void demodPass(const Image& in, const Image& guide, Coarse& coarse) {
    static const int kQy[9] = {0, 1, 1, 1, 1, 2, 0, 2, 2};
    static const int kQx[9] = {1, 0, 1, 3, 2, 1, 2, 0, 2};
    const float kPi = 3.14159265358979323846f;
    for (int cy = 0; cy < coarse.h; ++cy)
        for (int cx = 0; cx < coarse.w; ++cx)
            for (int py = 0; py < 2; ++py)
                for (int px = 0; px < 2; ++px) {
                    float re[9] = {0}, im[6] = {0};
                    for (int by = 0; by < 8; ++by)
                        for (int bx = 0; bx < 8; ++bx) {
                            const int pi = cy * 8 + by, pj = cx * 8 + bx;
                            const float z = in.at(2 * pj + px, 2 * pi + py) - guide.at(2 * pj + px, 2 * pi + py);
                            for (int k = 0; k < 9; ++k) {
                                const float ph = 2 * kPi * (kQy[k] * pi * 0.25f + kQx[k] * pj * 0.25f);
                                re[k] += z * std::cos(ph);
                                if (k < 6) im[k] += z * std::sin(ph);
                            }
                        }
                    coarse.at(0, py * 2 + px, cx, cy) = re[0] / 64;
                    coarse.at(1, py * 2 + px, cx, cy) = im[0] / 64;
                    coarse.at(2, py * 2 + px, cx, cy) = re[1] / 64;
                    coarse.at(3, py * 2 + px, cx, cy) = im[1] / 64;
                    coarse.at(4, py * 2 + px, cx, cy) = re[2] / 64;
                    coarse.at(5, py * 2 + px, cx, cy) = im[2] / 64;
                    coarse.at(6, py * 2 + px, cx, cy) = re[3] / 64;
                    coarse.at(7, py * 2 + px, cx, cy) = im[3] / 64;
                    coarse.at(8, py * 2 + px, cx, cy) = re[4] / 64;
                    coarse.at(9, py * 2 + px, cx, cy) = im[4] / 64;
                    coarse.at(10, py * 2 + px, cx, cy) = re[5] / 64;
                    coarse.at(11, py * 2 + px, cx, cy) = im[5] / 64;
                    coarse.at(12, py * 2 + px, cx, cy) = re[6] / 64;
                    coarse.at(13, py * 2 + px, cx, cy) = re[7] / 64;
                    coarse.at(14, py * 2 + px, cx, cy) = re[8] / 64;
                }
}

inline void gaussPass(const Coarse& src, Coarse& dst, bool vertical) {
    for (int ch = 0; ch < 15; ++ch)
        for (int ph = 0; ph < 4; ++ph)
            for (int y = 0; y < src.h; ++y)
                for (int x = 0; x < src.w; ++x) {
                    double acc = 0;
                    for (int k = -kCoarseR; k <= kCoarseR; ++k)
                        acc += double(kCoarseW[k + kCoarseR]) *
                               (vertical ? src.get(ch, ph, x, y + k) : src.get(ch, ph, x + k, y));
                    dst.at(ch, ph, x, y) = float(acc);
                }
}

inline void maskPass(const Image& src, Image& dst, bool vertical) {
    for (int y = 0; y < src.h; ++y)
        for (int x = 0; x < src.w; ++x) {
            double acc = 0;
            for (int k = -kMaskR; k <= kMaskR; ++k)
                acc += double(kMaskW[k + kMaskR]) *
                       double(vertical ? src.phaseAt(x, y, 0, k) : src.phaseAt(x, y, k, 0));
            dst.px[y * src.w + x] = std::min(1.0f, std::max(0.0f, float(acc)));
        }
}

inline void blendPass(const Image& in, const Image& guide, const Image& tmask, const Coarse& coarse,
                      Image& out) {
    const float kPi = 3.14159265358979323846f;
    for (int y = 0; y < in.h; ++y)
        for (int x = 0; x < in.w; ++x) {
            const int pi = y >> 1, pj = x >> 1, ph = ((y & 1) << 1) | (x & 1);
            const int cx = pj >> 3, cy = pi >> 3;
            float corr = 0;
            for (int k = 0; k < 15; ++k) {
                const float est = coarse.get(k, ph, cx, cy);
                const float phs = 2 * kPi * (kCQy[k] * pi * 0.25f + kCQx[k] * pj * 0.25f);
                corr += kCFac[k] * est * (kCIsIm[k] ? std::sin(phs) : std::cos(phs));
            }
            const float orig = in.at(x, y);
            const float g = guide.at(x, y);
            const float notch = (orig - g) - corr;
            const float t = tmask.at(x, y);
            out.px[y * in.w + x] = t * orig + (1 - t) * (g + notch);
        }
}

struct Result {
    Image guide, mask, out;
};

inline Result filter(const Image& in, bool fast) {
    Result r;
    r.guide.w = r.mask.w = r.out.w = in.w;
    r.guide.h = r.mask.h = r.out.h = in.h;
    r.guide.px.resize(size_t(in.w) * in.h);
    r.mask.px.resize(size_t(in.w) * in.h);
    r.out.px.resize(size_t(in.w) * in.h);
    Image tmp;
    tmp.w = in.w;
    tmp.h = in.h;
    tmp.px.resize(size_t(in.w) * in.h);
    guidePass(in, r.guide, fast);
    energyPass(in, r.guide, tmp);  // e in tmp
    Coarse c0, c1;
    c0.w = c1.w = in.w / 16;
    c0.h = c1.h = in.h / 16;
    c0.px.assign(size_t(15) * 4 * c0.w * c0.h, 0);
    c1.px.assign(size_t(15) * 4 * c0.w * c0.h, 0);
    demodPass(in, r.guide, c0);
    gaussPass(c0, c1, false);
    gaussPass(c1, c0, true);
    // mask: t_raw(tmp) -> smooth H (mask) -> smooth V (mask in place via second tmp)
    Image traw;
    traw.w = in.w;
    traw.h = in.h;
    traw.px.resize(size_t(in.w) * in.h);
    for (size_t i = 0; i < tmp.px.size(); ++i)
        traw.px[i] = std::min(1.0f, std::max(0.0f, (tmp.px[i] - kEFlat) / (kETex - kEFlat)));
    maskPass(traw, r.mask, false);
    maskPass(r.mask, tmp, true);
    r.mask = tmp;
    blendPass(in, r.guide, r.mask, c0, r.out);
    return r;
}

}  // namespace cpu
}  // namespace quadfix
